#!/usr/bin/env node
// D6 Kitchens — builds /updates/ pages and /feed.xml from _updates/*.md
// Zero dependencies. Usage: node scripts/build-updates.mjs [siteRoot]
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(process.argv[2] || path.join(path.dirname(new URL(import.meta.url).pathname), '..'));
const SITE = 'https://d6kitchens.com';
const SRC = path.join(ROOT, '_updates');
const OUT = path.join(ROOT, 'updates');
const MARKER = '<!-- generated by scripts/build-updates.mjs -->';
const NOW = process.env.BUILD_TIME ? new Date(process.env.BUILD_TIME) : new Date();
const MIME = { '.jpg':'image/jpeg', '.jpeg':'image/jpeg', '.png':'image/png', '.webp':'image/webp', '.gif':'image/gif', '.avif':'image/avif' };

const esc = s => String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const errors = [];

// ---------- parse ----------
function parseFrontmatter(raw, file) {
  const m = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!m) { errors.push(`${file}: missing front matter`); return null; }
  const data = {};
  for (const line of m[1].split(/\r?\n/)) {
    const kv = line.match(/^([a-z_]+):\s*(.*)$/);
    if (kv) data[kv[1]] = kv[2].trim().replace(/^(["'])(.*)\1$/, '$2');
  }
  return { data, body: m[2] };
}

function inline(s) {
  return esc(s)
    .replace(/!\[([^\]]*)\]\(([^)\s]+)\)/g, '<img src="$2" alt="$1" loading="lazy">')
    .replace(/\[([^\]]+)\]\(([^)\s]+)\)/g, '<a href="$2">$1</a>')
    .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
    .replace(/\*([^*]+)\*/g, '<em>$1</em>');
}

function markdown(md) {
  const out = []; let para = []; let list = [];
  const flushP = () => { if (para.length) out.push(`<p>${inline(para.join(' '))}</p>`); para = []; };
  const flushL = () => { if (list.length) out.push(`<ul>${list.map(i => `<li>${inline(i)}</li>`).join('')}</ul>`); list = []; };
  for (const line of md.split(/\r?\n/)) {
    const h = line.match(/^(#{2,3})\s+(.*)$/);
    const li = line.match(/^[-*]\s+(.*)$/);
    if (h) { flushP(); flushL(); out.push(`<h${h[1].length}>${inline(h[2])}</h${h[1].length}>`); }
    else if (li) { flushP(); list.push(li[1]); }
    else if (!line.trim()) { flushP(); flushL(); }
    else { flushL(); para.push(line.trim()); }
  }
  flushP(); flushL();
  return out.join('\n');
}

// ---------- load & validate ----------
const posts = [];
const seen = new Map();
if (fs.existsSync(SRC)) {
  for (const f of fs.readdirSync(SRC).filter(f => f.endsWith('.md')).sort()) {
    const parsed = parseFrontmatter(fs.readFileSync(path.join(SRC, f), 'utf8'), f);
    if (!parsed) continue;
    const d = parsed.data;
    if ((d.status || 'draft') !== 'published') continue;           // drafts never ship
    for (const k of ['title', 'date', 'slug', 'description']) if (!d[k]) errors.push(`${f}: missing "${k}"`);
    if (d.slug && !/^[a-z0-9]+(-[a-z0-9]+)*$/.test(d.slug)) errors.push(`${f}: slug must be lowercase-kebab-case`);
    if (!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(:\d{2})?(Z|[+-]\d{2}:\d{2})$/.test(d.date || '')) errors.push(`${f}: date must be ISO 8601 with timezone, e.g. 2026-10-01T09:00:00+04:00`);
    const date = new Date(d.date);
    if (isNaN(date)) continue;
    if (date > NOW) continue;                                        // scheduled: publish on a later build
    if (seen.has(d.slug)) errors.push(`${f}: duplicate slug "${d.slug}" (also in ${seen.get(d.slug)})`);
    seen.set(d.slug, f);

    let image = null;
    if (d.image) {
      if (/^https?:\/\//.test(d.image)) image = { url: d.image };
      else {
        const rel = d.image.replace(/^\/+/, '');
        const abs = path.join(ROOT, rel);
        const type = MIME[path.extname(rel).toLowerCase()];
        if (!fs.existsSync(abs)) errors.push(`${f}: image not found: /${rel}`);
        else if (!type) errors.push(`${f}: unsupported image type: /${rel}`);
        else image = { url: `${SITE}/${rel}`, path: `/${rel}`, type, length: fs.statSync(abs).size };
      }
      if (image && !d.image_alt) errors.push(`${f}: image_alt is required when image is set`);
      if (image) image.alt = d.image_alt || '';
    }
    const dayTag = d.date.slice(0, 10);
    posts.push({
      ...d, date, image,
      url: `${SITE}/updates/${d.slug}/`,
      guid: d.guid || `tag:d6kitchens.com,${dayTag}:updates/${d.slug}`,
      html: markdown(parsed.body),
    });
  }
}
if (errors.length) { console.error('Update build failed:\n  ' + errors.join('\n  ')); process.exit(1); }
posts.sort((a, b) => b.date - a.date);

// ---------- templates ----------
const displayDate = d => d.toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric', timeZone: 'Asia/Dubai' });

const page = ({ title, description, canonical, ogImage, main }) => `<!DOCTYPE html>
${MARKER}
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${esc(title)}</title>
<meta name="description" content="${esc(description)}">
<link rel="canonical" href="${canonical}">
<link rel="alternate" type="application/rss+xml" title="D6 Kitchens updates" href="/feed.xml">
<meta property="og:title" content="${esc(title)}">
<meta property="og:description" content="${esc(description)}">
<meta property="og:url" content="${canonical}">
${ogImage ? `<meta property="og:image" content="${ogImage}">\n` : ''}<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,300;0,9..144,500;0,9..144,600;0,9..144,700;1,9..144,500&family=Inter:wght@400;500;600&family=IBM+Plex+Mono:wght@400;500;600&display=swap" rel="stylesheet">
<style>
  :root{--ink:#1A1613;--paper:#FFFFFF;--paper-dim:#F6F5F3;--turmeric:#E8940A;--steel:#8A8480;--line-on-light:rgba(26,22,19,0.12);--maxw:1160px;}
  *{box-sizing:border-box;}
  body{margin:0;background:var(--paper);color:var(--ink);font-family:'Inter',sans-serif;-webkit-font-smoothing:antialiased;font-size:16px;line-height:1.55;}
  h1,h2,h3{font-family:'Fraunces',serif;font-weight:600;letter-spacing:-0.01em;margin:0;}
  a{color:inherit;} img{max-width:100%;display:block;height:auto;}
  ::selection{background:var(--turmeric);color:var(--ink);}
  a:focus-visible{outline:2px solid var(--turmeric);outline-offset:3px;}
  .wrap{max-width:var(--maxw);margin:0 auto;padding:0 32px;}
  header.nav{position:sticky;top:0;z-index:50;background:rgba(255,255,255,0.94);backdrop-filter:blur(8px);border-bottom:1px solid var(--line-on-light);}
  .nav-inner{max-width:var(--maxw);margin:0 auto;padding:0 32px;height:64px;display:flex;align-items:center;justify-content:space-between;}
  .brandmark{display:flex;align-items:center;gap:10px;font-family:'Fraunces',serif;font-weight:600;font-size:20px;text-decoration:none;}
  .brandmark .dot{width:8px;height:8px;border-radius:50%;background:var(--turmeric);}
  .nav-cta{font-family:'IBM Plex Mono',monospace;font-size:12px;letter-spacing:.05em;background:var(--turmeric);padding:8px 14px;border-radius:2px;text-decoration:none;white-space:nowrap;}
  main{padding:88px 0 120px;}
  .intro h1{font-size:clamp(36px,5vw,56px);line-height:1.05;}
  .intro p{color:var(--steel);max-width:52ch;margin:16px 0 0;font-size:17px;}
  .list{list-style:none;margin:56px 0 0;padding:0;border-top:1px solid var(--line-on-light);}
  .list li{border-bottom:1px solid var(--line-on-light);}
  .list a{display:grid;grid-template-columns:180px 1fr;gap:32px;padding:32px 0;text-decoration:none;}
  .list a:hover h2{color:var(--turmeric);}
  .list time{font-family:'IBM Plex Mono',monospace;font-size:13px;color:var(--steel);padding-top:6px;}
  .list h2{font-size:26px;line-height:1.2;transition:color .2s;}
  .list p{margin:8px 0 0;color:var(--steel);max-width:60ch;}
  .empty{margin-top:56px;padding:40px 0;border-top:1px solid var(--line-on-light);color:var(--steel);}
  article{max-width:720px;}
  article .meta{font-family:'IBM Plex Mono',monospace;font-size:13px;color:var(--steel);margin-bottom:20px;display:block;}
  article h1{font-size:clamp(34px,5vw,52px);line-height:1.08;}
  article .lede{font-size:19px;color:var(--steel);margin:20px 0 0;}
  article figure{margin:40px 0 0;} article figure img{width:100%;border-radius:2px;}
  .body{margin-top:40px;font-size:17px;line-height:1.7;}
  .body h2{font-size:28px;margin:44px 0 12px;} .body h3{font-size:21px;margin:32px 0 8px;}
  .body p,.body ul{margin:0 0 20px;} .body a{text-decoration-color:var(--turmeric);text-underline-offset:3px;}
  .back{display:inline-block;margin-top:56px;font-family:'IBM Plex Mono',monospace;font-size:13px;color:var(--steel);text-decoration:none;}
  .back:hover{color:var(--ink);}
  footer{border-top:1px solid var(--line-on-light);padding:32px 0;}
  footer .wrap{display:flex;justify-content:space-between;flex-wrap:wrap;gap:16px;font-size:13px;color:var(--steel);}
  footer a{text-decoration:none;} footer a:hover{color:var(--ink);}
  @media(max-width:700px){.wrap,.nav-inner{padding:0 20px;} main{padding:56px 0 88px;} .list a{grid-template-columns:1fr;gap:8px;}}
</style>
</head>
<body>
<header class="nav">
  <div class="nav-inner">
    <a href="/" class="brandmark"><span class="dot"></span>D6 Kitchens</a>
    <a href="/#contact" class="nav-cta">PARTNER WITH US</a>
  </div>
</header>
<main><div class="wrap">
${main}
</div></main>
<footer><div class="wrap"><span>D6 Kitchens</span><span><a href="/updates/">Updates</a> &nbsp; <a href="/feed.xml">RSS</a> &nbsp; <a href="mailto:hello@d6kitchens.com">hello@d6kitchens.com</a></span></div></footer>
</body>
</html>
`;

const indexMain = `<div class="intro">
  <h1>Updates</h1>
  <p>Announcements, new kitchen brands, launches and milestones from D6 Kitchens.</p>
</div>
${posts.length ? `<ul class="list">
${posts.map(p => `  <li><a href="/updates/${p.slug}/"><time datetime="${p.date.toISOString()}">${displayDate(p.date)}</time><div><h2>${esc(p.title)}</h2><p>${esc(p.description)}</p></div></a></li>`).join('\n')}
</ul>` : `<p class="empty">No updates have been published yet. Follow the <a href="/feed.xml">RSS feed</a> to hear about the first one.</p>`}`;

// ---------- write pages ----------
fs.mkdirSync(OUT, { recursive: true });
// remove previously generated post folders that no longer have a published source
for (const dir of fs.readdirSync(OUT, { withFileTypes: true })) {
  if (!dir.isDirectory() || posts.some(p => p.slug === dir.name)) continue;
  const f = path.join(OUT, dir.name, 'index.html');
  if (fs.existsSync(f) && fs.readFileSync(f, 'utf8').includes(MARKER)) fs.rmSync(path.join(OUT, dir.name), { recursive: true });
}
fs.writeFileSync(path.join(OUT, 'index.html'), page({
  title: 'Updates — D6 Kitchens',
  description: 'Announcements, new kitchen brands, launches and milestones from D6 Kitchens.',
  canonical: `${SITE}/updates/`, main: indexMain,
}));
for (const p of posts) {
  fs.mkdirSync(path.join(OUT, p.slug), { recursive: true });
  fs.writeFileSync(path.join(OUT, p.slug, 'index.html'), page({
    title: `${p.title} — D6 Kitchens`, description: p.description, canonical: p.url, ogImage: p.image?.url,
    main: `<article>
  <time class="meta" datetime="${p.date.toISOString()}">${displayDate(p.date)}</time>
  <h1>${esc(p.title)}</h1>
  <p class="lede">${esc(p.description)}</p>
  ${p.image ? `<figure><img src="${p.image.path || p.image.url}" alt="${esc(p.image.alt)}"></figure>` : ''}
  <div class="body">
${p.html}
  </div>
  <a class="back" href="/updates/">All updates</a>
</article>`,
  }));
}

// ---------- feed ----------
const item = p => `    <item>
      <title>${esc(p.title)}</title>
      <link>${p.url}</link>
      <guid isPermaLink="${p.guid === p.url}">${esc(p.guid)}</guid>
      <pubDate>${p.date.toUTCString()}</pubDate>
      <description>${esc(p.description)}</description>
      <content:encoded><![CDATA[${(p.image ? `<p><img src="${p.image.url}" alt="${esc(p.image.alt)}"></p>\n` : '') + p.html.replace(/src="\//g, `src="${SITE}/`).replace(/href="\//g, `href="${SITE}/`).replace(/]]>/g, ']]]]><![CDATA[>')}]]></content:encoded>
${p.image?.length ? `      <enclosure url="${p.image.url}" length="${p.image.length}" type="${p.image.type}"/>\n` : ''}${p.image ? `      <media:content url="${p.image.url}" medium="image"${p.image.type ? ` type="${p.image.type}"` : ''}/>\n` : ''}    </item>`;

const feed = `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:media="http://search.yahoo.com/mrss/">
  <channel>
    <title>D6 Kitchens — Updates</title>
    <link>${SITE}/updates/</link>
    <description>Announcements, new kitchen brands, launches and company milestones from D6 Kitchens.</description>
    <language>en</language>
    <atom:link href="${SITE}/feed.xml" rel="self" type="application/rss+xml"/>
${posts.length ? `    <lastBuildDate>${posts[0].date.toUTCString()}</lastBuildDate>\n` : ''}${posts.map(item).join('\n')}${posts.length ? '\n' : ''}  </channel>
</rss>
`;
fs.writeFileSync(path.join(ROOT, 'feed.xml'), feed);
console.log(`Built ${posts.length} published update(s) → /updates/ and /feed.xml`);
